name: run-test

inputs:
  sha:
    required: true
    type: string

  os:
    required: true
    type: string

  github-token:
    required: true
    type: string


runs:
  using: composite
  steps:
    - name: Download compiled artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: artifact-${{ inputs.sha }}-${{ inputs.os }}
        workflow: build-many.yml

    - name: Run and update
      run: |
        mv lgs* _lgs
        chmod +x _lgs

        ./_lgs >> my-github-stars.md
        gh gist edit ada2117bd8c73a1e94e49580fd5c7cf7 --add my-github-stars.md
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
