name: build-and-push


inputs:
  tagged-name:
    required: true
    description: The tagged Docker image name (user/repo:tag)

  dockerhub-token:
    required: true
    description: Authentication token for Docker Hub


runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: caian
        password: ${{ inputs.dockerhub-token }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ inputs.tagged-name }}
