name: build-many

on:
  push:
    branches:
      - master
    tags:
      - "v*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  multi-os:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Cache Go packages
        id: cache-go-pkgs
        uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        if: steps.cache-go-pkgs.outputs.cache-hit != 'true'
        run: go get

      - name: Build
        run: make build
