name: release-many

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  wait-build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to finish
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.AUTH_TOKEN }}
          wait-interval: 10
          running-workflow-name: wait-build
          allowed-conclusions: success,skipped,neutral

  push-docker-image:
    runs-on: ubuntu-latest
    env:
      image-name: caian/list-github-stars

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Retrieve metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.image-name }}
          tags: type=semver,pattern={{version}}

      - name: Build and push "${{ steps.meta.outputs.tags }}" tag
        uses: ./.github/actions/build-and-push
        with:
          tagged-name: ${{ steps.meta.outputs.tags }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  release-many:
    runs-on: ubuntu-latest
    needs: wait-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download linux artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: artifact-${{ github.sha }}-ubuntu-latest
          path: linux-artifact
          workflow: build-many.yml

      - name: Download macos artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: artifact-${{ github.sha }}-macos-latest
          path: macos-artifact
          workflow: build-many.yml

      - name: Download windows artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: artifact-${{ github.sha }}-windows-latest
          path: windows-artifact
          workflow: build-many.yml

      - name: Release new version
        run: |
          export LINUX_ARTIFACT="lgs-linux-$TAG"
          mv "linux-artifact/list-github-stars" "$LINUX_ARTIFACT"

          export MACOS_ARTIFACT="lgs-macos-$TAG"
          mv "macos-artifact/list-github-stars" "$MACOS_ARTIFACT"

          export WINDOWS_ARTIFACT="lgs-windows-$TAG.exe"
          mv "windows-artifact/list-github-stars.exe" "$WINDOWS_ARTIFACT"

          curl -L -o vrelease https://github.com/vrelease/vrelease/releases/download/v0.3.2/vrelease-linux
          chmod +x vrelease

          ./vrelease \
            -add-checksum \
            -attach "$LINUX_ARTIFACT" \
            -attach "$MACOS_ARTIFACT" \
            -attach "$WINDOWS_ARTIFACT"
        env:
          TAG: ${{ github.ref_name }}
          VRELEASE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
