name: test-many

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"

defaults:
  run:
    shell: bash

jobs:
  # ..........................................................................
  wait-build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to finish
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
          running-workflow-name: wait-build

  # ..........................................................................
  on-linux:
    runs-on: ubuntu-latest
    needs: wait-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare and run tests
        uses: ./.github/actions/test-routine
        with:
          sha: ${{ github.sha }}
          os: ${{ env.RUNNER_OS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # ..........................................................................
  on-macos:
    runs-on: macos-latest
    needs: on-linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare and run tests
        uses: ./.github/actions/test-routine
        with:
          sha: ${{ github.sha }}
          os: ${{ env.RUNNER_OS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # ..........................................................................
  on-windows:
    runs-on: windows-latest
    needs: on-macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare and run tests
        uses: ./.github/actions/test-routine
        with:
          sha: ${{ github.sha }}
          os: ${{ env.RUNNER_OS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
