name: test-many

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
# pull_request:
#   branches:
#     - "*"
#   paths-ignore:
#     - "**.md"

defaults:
  run:
    shell: bash

jobs:
  # ..........................................................................
  wait-build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to finish
        uses: lewagon/wait-on-check-action@v1.1.1
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.AUTH_TOKEN }}
          wait-interval: 20
          running-workflow-name: wait-build
          allowed-conclusions: success,skipped,neutral

  # ..........................................................................
  on-linux:
    runs-on: ubuntu-latest
    needs: wait-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare and run tests
        uses: ./.github/actions/run-test
        with:
          sha: ${{ github.sha }}
          os: ubuntu-latest
          github-token: ${{ secrets.AUTH_TOKEN }}

  # ..........................................................................
  on-macos:
    runs-on: macos-latest
    needs: on-linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare and run tests
        uses: ./.github/actions/run-test
        with:
          sha: ${{ github.sha }}
          os: macos-latest
          github-token: ${{ secrets.AUTH_TOKEN }}

  # ..........................................................................
  on-windows:
    runs-on: windows-latest
    needs: on-macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare and run tests
        uses: ./.github/actions/run-test
        with:
          sha: ${{ github.sha }}
          os: windows-latest
          github-token: ${{ secrets.AUTH_TOKEN }}

  # ..........................................................................
  on-docker:
    runs-on: ubuntu-latest
    needs: on-windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build image
        run: docker build -t list-github-stars .

      - name: Run and update
        run: |
          docker run \
            --rm \
            -e GITHUB_TOKEN="$GITHUB_TOKEN" \
            list-github-stars >> my-github-stars.md

          gh gist edit ada2117bd8c73a1e94e49580fd5c7cf7 --add my-github-stars.md
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
